### ISSUE TITLE
git: error: unknown option `no-edit' or `config` or `local`

### ISSUE THREAD

**Issue by daniltulin** [Linuxbrew/legacy-linuxbrew#1071] opened 2016-04-13 15:32 UTC
I have git 1.7.1 
I try to 

``` sh
$ brew install python3
==> Tapping homebrew/dupes
error: unknown option `config
```

or 

``` sh
$ brew update
error: unknown option `no-edit'
```

That mistakes about the age of my git's version, but I can't find out what version is better to use
Under some circumstances I can't use cutting-edge 2.\* versions :(

**Comment by sjackman** [comment] 2016-04-13 17:37
I don't know which minimum version is required either. =p
Try `brew install git`

**Comment by sjackman** [comment] 2016-04-13 17:39
I thought `git config` went back to day one of git? Strange. Please report
```sh
git --version
git config user.name
```

**Comment by sjackman** [comment] 2016-04-13 17:41
Never mind my previous message. The command that's causing the error is: `git clone --config`.
We need to add a `brew doctor` check to check the version of `git`.
`brew install git` should fix your trouble.

**Comment by tulindanil** [comment] 2016-04-13 19:57
Thank you for the answer! 
I suppose that the only way to install git is installing it from sources

Cause brew uses git to fetch git

**Comment by rwhogg** [comment] 2016-04-13 21:09
I thought such a doctor check already existed. I remember seeing it just yesterday. Might just have to change the minimum required version.

On April 13, 2016 12:57:16 PM PDT, Tulin Daniil <notifications@github.com> wrote:
>Thank you for the answer! 
>I suppose that the only way to install git is installing it from
>sources
>
>Cause brew uses git to fetch git
>
>---
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/Linuxbrew/linuxbrew/issues/1071#issuecomment-209621714

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by sjackman** [comment] 2016-04-13 22:32
@tulindanil Please report `brew doctor`

**Comment by sjackman** [comment] 2016-04-13 22:34
```
            An outdated version of Git was detected in your PATH.
            Git 1.7.10 or newer is required to perform checkouts over HTTPS from GitHub.
            Please upgrade: brew #{git_upgrade_cmd} git
```

**Comment by sjackman** [comment] 2016-04-13 22:36
> Cause brew uses git to fetch git

Are you sure? It shouldn't. It's a bug if it does.

```
$ brew install git -v
==> Installing dependencies for git: patchelf, zlib, binutils, linux-headers, glibc, xz, gmp, gpatch, mpfr, libmpc, isl, gcc, makedepend, openssl, pkg-config, curl, expat
```

**Comment by sjackman** [comment] 2016-04-13 22:39
It would be helpful I think to run `Diagnostic::check_for_git` before `brew tap` or `brew update`. In fact, I though it did do this, but I guess not.

**Comment by tulindanil** [comment] 2016-04-14 00:11
It is my fault that I did not launch that command
But nevertheless it will be great if this information will be on your website!
```sh
$ brew doctor

...

Warning: An outdated version of Git was detected in your PATH.
Git 1.7.10 or newer is required to perform checkouts over HTTPS from GitHub.
Please upgrade: brew install git

...

```

And my git is really dummy 

```sh
$ brew install git -v
==> Tapping homebrew/dupes
git clone https://github.com/Homebrew/homebrew-dupes /home-local/gratom/satom12/.linuxbrew/Library/Taps/homebrew/homebrew-dupes --config core.autocrlf=false --depth=1
error: unknown option `config'
...
Error: Failure while executing: git clone https://github.com/Homebrew/homebrew-dupes /home-local/gratom/satom12/.linuxbrew/Library/Taps/homebrew/homebrew-dupes --config core.autocrlf=false --depth=1
```

**Comment by sjackman** [comment] 2016-04-14 00:15
I want to figure out why your `git` depends on `homebrew/dupes`, but my `git` does not.
Please report `brew deps git` and `brew deps --tree git`

**Comment by sjackman** [comment] 2016-04-14 00:18
You can also try `brew install -s git`

**Comment by tulindanil** [comment] 2016-04-14 01:08
```
$ brew deps git
Error: No available formula with the name "homebrew/dupes/m4" 
Please tap it and then try again: brew tap homebrew/dupes
```

```
$ brew deps --tree git
git (required dependencies)
├── xz
├── xz
├── xz
├── openssl
│   ├── make depend
│   │   └── pig-config
│   ├── patch
│   │   └── xz
│   ├── patch
│   │   └── xz
│   └── lib
├── curl
│   ├── pig-config
│   ├── patch
│   │   └── xz
│   └── openssl
│       ├── make depend
│       │   └── pig-config
│       ├── patch
│       │   └── xz
│       ├── patch
│       │   └── xz
│       └── lib
└── expat
```

```
$ brew install -s git
==> Tapping homebrew/dupes
error: unknown option `config'
```

**Comment by sjackman** [comment] 2016-04-14 01:15
I can reproduce this bug on CentOS 6 with git 1.7.1.

```
$ brew tap homebrew/dupes
==> Tapping homebrew/dupes
error: unknown option `config'
usage: git clone [options] [--] <repo> [<dir>]
…
Error: Failure while executing: git clone https://github.com/Homebrew/homebrew-dupes /home/sjackman/.linuxbrew/Library/Taps/homebrew/homebrew-dupes --config core.autocrlf=false --depth=1
```

**Comment by sjackman** [comment] 2016-04-14 01:18
> But nevertheless it will be great if this information will be on your website!

There isn't a `git` dependency listed, because `brew install git` is supposed to work. It's a bug that it doesn't.

**Comment by sjackman** [comment] 2016-04-14 01:23
Now that I can reproduce this bug, I'll work on figuring it out.

```
$ brew deps git --skip-optional
curl
expat
gpatch
makedepend
openssl
pkg-config
xz
zlib
```

```
$ brew deps git
Error: No available formula with the name "homebrew/dupes/m4" 
Please tap it and then try again: brew tap homebrew/dupes
```

The tapping logic is trying to tap due to an optional dependency, even though it won't be installed.

**Comment by sjackman** [comment] 2016-04-14 01:25
Try
```sh
brew install patchelf
brew install zlib
brew install binutils
brew install linux-headers
brew install glibc
brew install xz
brew install gmp
brew install gpatch
brew install mpfr
brew install libmpc
brew install isl
brew install gcc
brew install makedepend
brew install openssl
brew install pkg-config
brew install curl
brew install expat
brew install git
```

**Comment by sjackman** [comment] 2016-04-14 01:27
@ilovezfs Hi, Joe. When installing `git`, the tapping logic is trying to tap `Homebrew/dupes` due to an optional dependency of `git` (somewhere down the dependency chain), which isn't actually going to be installed. The problem is that `git` isn't yet installed, so the tapping fails.

**Comment by sjackman** [comment] 2016-04-14 01:28
Related:
```
$ brew deps git
Error: No available formula with the name "homebrew/dupes/m4" 
Please tap it and then try again: brew tap homebrew/dupes
```
I'm less worried about this error. In fact, I'm just fine with the current behaviour.

**Comment by maxim-belkin** [comment] 2016-04-14 17:10
I think this issue will be resolved one day by creating a statically-linked-git formula following the guides from [here](en.newinstance.it/2011/02/27/how-to-create-a-statically-linked-version-of-git-binaries/).

**Comment by sjackman** [comment] 2016-04-14 18:56
Does anyone know whether the `git` bottle is relocatable in practice? It's not currently marked as being `cellar :any`.

**Comment by sjackman** [comment] 2016-04-14 18:57
> In fact, I'm just fine with the current behaviour.

Except that I never understood why `--skip-optional` isn't the default behaviour. I think that `--with-all-options` should be the opt-in behaviour.

**Comment by ilovezfs** [comment] 2016-04-15 05:22
@sjackman See https://github.com/Homebrew/legacy-homebrew/issues/50066#issuecomment-199201268

**Comment by sjackman** [comment] 2016-04-16 22:59
See https://github.com/Homebrew/brew/pull/92

**Comment by DoomHammer** [comment] 2016-04-17 21:19
As for `git` versions and `brew doctor` complaining: https://github.com/ipython/ipython/issues/2195/ . It seems releases after 1.7.9.5 *should* suffice.

**Comment by sjackman** [comment] 2016-04-18 05:36
Can we close this issue since we have the `brew doctor` check?

**Comment by njia** [comment] 2016-05-04 00:50
I had similar problem, when I tried to upgrade from linuxbrew git 2.8 to 2.8.2 I got following error

`Error: Failure while executing: git config --local --replace-all homebrew.private false`

The solution for me is to remove git 1.7.1 from CenOS but I am surprised to see this problem as I have linuxbrew git comes first in my $PATH.

```
[njia@centos6 Desktop]$ brew outdated
readline (6.3.8 < 6.3.8_1)
vim (7.4.1655 < 7.4.1795)
git (2.8.0 < 2.8.2)
sqlite (3.11.0_1 < 3.12.2)
ansible (2.0.1.0 < 2.0.2.0)
openssl (1.0.2g < 1.0.2h)
[njia@centos6 Desktop]$ brew upgrade git
==> Upgrading 1 outdated package, with result:
git 2.8.2
==> Upgrading git
==> Installing dependencies for git: openssl
==> Installing git dependency: openssl
error: unknown option `local'
usage: git config [options]

Config file location
    --global              use global config file
    --system              use system config file
    -f, --file <FILE>     use given config file

Action
    --get                 get value: name [value-regex]
    --get-all             get all values: key [value-regex]
    --get-regexp          get values for regexp: name-regex [value-regex]
    --replace-all         replace all matching variables: name value [value_regex]
    --add                 adds a new variable: name value
    --unset               removes a variable: name [value-regex]
    --unset-all           removes all matches: name [value-regex]
    --rename-section      rename section: old-name new-name
    --remove-section      remove a section: name
    -l, --list            list all
    -e, --edit            opens an editor
    --get-color <slot>    find the color configured: [default]
    --get-colorbool <slot>
                          find the color setting: [stdout-is-tty]

Type
    --bool                value is "true" or "false"
    --int                 value is decimal number
    --bool-or-int         value is --bool or --int
    --path                value is a path (file or directory name)

Other
    -z, --null            terminate values with NUL byte

Error: Failure while executing: git config --local --replace-all homebrew.private false

[njia@centos6 Desktop]$ su -
Password: 
[root@centos6 ~]# yum erase git
Loaded plugins: fastestmirror, refresh-packagekit, security
Setting up Remove Process
Resolving Dependencies
--> Running transaction check
---> Package git.x86_64 0:1.7.1-4.el6_7.1 will be erased
--> Processing Dependency: git = 1.7.1-4.el6_7.1 for package: perl-Git-1.7.1-4.el6_7.1.noarch
--> Running transaction check
---> Package perl-Git.noarch 0:1.7.1-4.el6_7.1 will be erased
--> Finished Dependency Resolution

Dependencies Resolved

======================================================================================================================================
 Package                       Arch                        Version                                Repository                     Size
======================================================================================================================================
Removing:
 git                           x86_64                      1.7.1-4.el6_7.1                        @updates                       15 M
Removing for dependencies:
 perl-Git                      noarch                      1.7.1-4.el6_7.1                        @updates                       35 k

Transaction Summary
======================================================================================================================================
Remove        2 Package(s)

Installed size: 15 M
Is this ok [y/N]: y
Downloading Packages:
Running rpm_check_debug
Running Transaction Test
Transaction Test Succeeded
Running Transaction
  Erasing    : git-1.7.1-4.el6_7.1.x86_64                                                                                         1/2 
  Erasing    : perl-Git-1.7.1-4.el6_7.1.noarch                                                                                    2/2 
  Verifying  : perl-Git-1.7.1-4.el6_7.1.noarch                                                                                    1/2 
  Verifying  : git-1.7.1-4.el6_7.1.x86_64                                                                                         2/2 

Removed:
  git.x86_64 0:1.7.1-4.el6_7.1                                                                                                        

Dependency Removed:
  perl-Git.noarch 0:1.7.1-4.el6_7.1                                                                                                   

Complete!
[root@centos6 ~]# exit
logout
[njia@centos6 Desktop]$ brew upgrade git
==> Upgrading 1 outdated package, with result:
git 2.8.2
==> Upgrading git
==> Installing dependencies for git: openssl
==> Installing git dependency: openssl
==> Downloading https://www.openssl.org/source/openssl-1.0.2h.tar.gz
curl: (35) SSL connect error
Trying a mirror...
==> Downloading https://dl.bintray.com/homebrew/mirror/openssl-1.0.2h.tar.gz
######################################################################## 100.0%
==> perl ./Configure --prefix=/home/njia/.linuxbrew/Cellar/openssl/1.0.2h --openssldir=/home/njia/.linuxbrew/etc/openssl no-ssl2 zlib-
==> make depend
==> make
==> make test
==> make install MANDIR=/home/njia/.linuxbrew/Cellar/openssl/1.0.2h/share/man MANSUFFIX=ssl
==> Downloading https://curl.haxx.se/ca/cacert-2016-04-20.pem
######################################################################## 100.0%
==> Caveats
A CA file has been bootstrapped using certificates from the system
keychain. To add additional certificates, place .pem files in
  /home/njia/.linuxbrew/etc/openssl/certs

and run
  /home/njia/.linuxbrew/opt/openssl/bin/c_rehash

==> Summary
/home/njia/.linuxbrew/Cellar/openssl/1.0.2h: 1,698 files, 14M, built in 4 minutes
==> Installing git
==> Downloading https://www.kernel.org/pub/software/scm/git/git-2.8.2.tar.xz
######################################################################## 100.0%
==> make install prefix=/home/njia/.linuxbrew/Cellar/git/2.8.2 sysconfdir=/home/njia/.linuxbrew/etc CC=/usr/bin/gcc CFLAGS=-Os -w -pip
==> make CC=/usr/bin/gcc CFLAGS=-Os -w -pipe -march=core2 LDFLAGS=-L/home/njia/.linuxbrew/lib -Wl,--dynamic-linker=/home/njia/.linuxbr
==> Downloading https://www.kernel.org/pub/software/scm/git/git-manpages-2.8.2.tar.xz
######################################################################## 100.0%
==> Downloading https://www.kernel.org/pub/software/scm/git/git-htmldocs-2.8.2.tar.xz
######################################################################## 100.0%
==> Caveats
The OS X keychain credential helper has been installed to:
  /home/njia/.linuxbrew/bin/git-credential-osxkeychain

The "contrib" directory has been installed to:
  /home/njia/.linuxbrew/share/git-core/contrib

Bash completion has been installed to:
  /home/njia/.linuxbrew/etc/bash_completion.d

zsh completion has been installed to:
  /home/njia/.linuxbrew/share/zsh/site-functions


Emacs Lisp files have been installed to:
  /home/njia/.linuxbrew/share/emacs/site-lisp/git
==> Summary
/home/njia/.linuxbrew/Cellar/git/2.8.2: 1,342 files, 29.1M, built in 1 minute 3 seconds
```

**Comment by sjackman** [comment] 2016-05-04 16:19
Hi, Nija. The workaround for your issue is
```sh
PATH=`brew --prefix git`/bin:$PATH brew upgrade git
```

**Closed** 2017-11-27 02:26 UTC
Labels: bug
