### ISSUE TITLE
libgcrypt failed to build on Ubuntu Trusty

### ISSUE THREAD

**Issue by mistydemeo** [Linuxbrew/legacy-linuxbrew#470] opened 2015-07-08 17:33 UTC
_From @bxm156 on July 8, 2015 17:28_

https://gist.github.com/c9ac647b584aa11dedbd

```
make[2]: *** [check-TESTS] Error 1
make[2]: Leaving directory `/tmp/libgcrypt20150708-22643-ognl02/libgcrypt-1.6.3/tests'
make[1]: *** [check-am] Error 2
make[1]: Leaving directory `/tmp/libgcrypt20150708-22643-ognl02/libgcrypt-1.6.3/tests'
make: *** [check-recursive] Error 1
```

_Copied from original issue: Homebrew/homebrew#41487_

**Comment by sjackman** [comment] 2015-07-08 17:51
`make check` fails.

https://gist.github.com/anonymous/c9ac647b584aa11dedbd#file-03-make-L57-L58
```
/bin/bash: line 5: 29357 Segmentation fault      (core dumped) GCRYPT_IN_REGRESSION_TEST=1 ${dir}$tst
FAIL: basic
```

https://gist.github.com/anonymous/c9ac647b584aa11dedbd#file-03-make-L148-L149
```
SALSA20     /bin/bash: line 5: 29416 Segmentation fault      (core dumped) GCRYPT_IN_REGRESSION_TEST=1 ${dir}$tst
FAIL: benchmark
```

https://gist.github.com/anonymous/c9ac647b584aa11dedbd#file-03-make-L148-L149
```
     STREAM enc | /bin/bash: line 5: 29422 Segmentation fault      (core dumped) GCRYPT_IN_REGRESSION_TEST=1 ${dir}$tst
FAIL: bench-slope
```

**Comment by sjackman** [comment] 2015-07-08 17:54
I'm not sure why these tests fail, but I am able to reproduce the issue. Please report this bug to the upstream developers. 

http://www.gnu.org/software/libgcrypt/
http://lists.gnupg.org/mailman/listinfo/gcrypt-devel

**Comment by DoomHammer** [comment] 2015-10-06 17:41
As a workaround you may `brew install --debug libgcrypt` and select ignore (2). It should install without problems.

**Comment by fuzzy76** [comment] 2016-02-23 08:30
I'm guessing this is a duplicate of #230

**Comment by iMichka** [comment] 2017-10-24 12:39
We have a bottle for libgcrypt now, so I guess this has been fixed at one point, either by us or by upstream.

If there are still problems with this, please open a new issue in our new repo: https://github.com/Linuxbrew/homebrew-core

**Closed by iMichka** 2017-10-24 12:39 UTC
Labels: build-error, upstream
