### ISSUE TITLE
google-perftools  2.4: Checking if nanosleep requires any libraries... configure: error: cannot find the nanosleep function

### ISSUE THREAD

**Issue by LeeBergstrand** [Linuxbrew/legacy-linuxbrew#256] opened 2015-01-23 18:41 UTC
Linux Configuration

---

Distributor ID: Ubuntu
Description:    Ubuntu 14.04.1 LTS
Release:    14.04
Codename:   trusty

---

```
syntax@JVHLabVM:~$ brew install google-perftools
==> Downloading https://googledrive.com/host/0B6NtGsLhIcf7MWxMMF9JdTN3UVk/gperftools-2.4.tar.gz
Already downloaded: /home/syntax/.cache/Homebrew/google-perftools-2.4.tar.gz
==> Patching
==> ./configure --prefix=/home/syntax/.linuxbrew/Cellar/google-perftools/2.4
checking for __builtin_expect()... yes
checking for __environ... yes
checking for __thread... yes
checking if __malloc_hook is declared volatile... yes
checking if nanosleep requires any libraries... configure: error: cannot find the nanosleep function

READ THIS: https://github.com/Homebrew/linuxbrew/blob/master/share/doc/homebrew/Troubleshooting.md#troubleshooting
```

**Comment by LeeBergstrand** [comment] 2015-01-23 18:42
Error when brew installing google-perftools.

**Comment by saketkc** [comment] 2015-01-23 20:44
I think it is this: https://bugs.launchpad.net/ubuntu/+source/gcc-4.6/+bug/1269803

**Comment by sjackman** [comment] 2015-02-02 18:06
You can try `brew install gcc`.

**Comment by sjackman** [comment] 2015-02-02 18:07
I'm closing this issue. Feel free to reopen it if the above suggestion does not work.

**Comment by LeeBergstrand** [comment] 2015-02-02 18:35
syntax@JVHLabVM:~$ brew install gcc
Warning: gcc-4.9.2_1 already installed

I also brew uninstall gcc and still got the same error as above. 
My built in gcc is gcc version 4.8.2 (Ubuntu 4.8.2-19ubuntu1)

**Comment by LeeBergstrand** [comment] 2015-02-02 18:40
Re-brew installed gcc. Lets, see if that works.

**Comment by sjackman** [comment] 2015-02-02 22:27
Try `brew install google-perftools --cc=gcc-4.9`

**Comment by LeeBergstrand** [comment] 2015-02-03 04:25
Same Error:

brew install google-perftools --cc=gcc-4.9
==> Downloading https://googledrive.com/host/0B6NtGsLhIcf7MWxMMF9JdTN3UVk/gperftools-2.4.tar.gz
Already downloaded: /home/syntax/.cache/Homebrew/google-perftools-2.4.tar.gz
==> ./configure --prefix=/home/syntax/.linuxbrew/Cellar/google-perftools/2.4
checking for __builtin_expect()... yes
checking for __environ... yes
checking for __thread... yes
checking if __malloc_hook is declared volatile... yes
checking if nanosleep requires any libraries... configure: error: cannot find the nanosleep function

READ THIS: https://github.com/Homebrew/linuxbrew/blob/master/share/doc/homebrew/Troubleshooting.md#troubleshooting

**Comment by LeeBergstrand** [comment] 2015-02-03 04:28
Still same error:

brew install google-perftools --cc=gcc-4.9
==> Downloading https://googledrive.com/host/0B6NtGsLhIcf7MWxMMF9JdTN3UVk/gperftools-2.4.tar.gz
Already downloaded: /home/syntax/.cache/Homebrew/google-perftools-2.4.tar.gz
==> ./configure --prefix=/home/syntax/.linuxbrew/Cellar/google-perftools/2.4
checking for __builtin_expect()... yes
checking for __environ... yes
checking for __thread... yes
checking if __malloc_hook is declared volatile... yes
checking if nanosleep requires any libraries... configure: error: cannot find the nanosleep function

READ THIS: https://github.com/Homebrew/linuxbrew/blob/master/share/doc/homebrew/Troubleshooting.md#troubleshooting

**Comment by LeeBergstrand** [comment] 2015-02-03 04:32
I did some quick searches for the code producing this message. May be useful.

https://github.com/frankee/Cetty/blob/8ad3d1adb321a68a1505d59656b4f9dde8b46efb/thirdparty/google-perftools-1.7/m4/acx_nanosleep.m4

**Comment by LeeBergstrand** [comment] 2015-02-03 04:35
From source code of google-perftools 2.4:

# Check for support for nanosleep.  It's defined in <time.h>, but on
# some systems, such as solaris, you need to link in a library to use it.
# We set acx_nanosleep_ok if nanosleep is supported; in that case,
# NANOSLEEP_LIBS is set to whatever libraries are needed to support
# nanosleep.

AC_DEFUN([ACX_NANOSLEEP],
[AC_MSG_CHECKING(if nanosleep requires any libraries)
 AC_LANG_SAVE
 AC_LANG_C
 acx_nanosleep_ok="no"
 NANOSLEEP_LIBS=
 # For most folks, this should just work
 AC_TRY_LINK([#include <time.h>],
             [static struct timespec ts; nanosleep(&ts, NULL);],
             [acx_nanosleep_ok=yes])
 # For solaris, we may  need -lrt
 if test "x$acx_nanosleep_ok" != "xyes"; then
   OLD_LIBS="$LIBS"
   LIBS="-lrt $LIBS"
   AC_TRY_LINK([#include <time.h>],
               [static struct timespec ts; nanosleep(&ts, NULL);],
               [acx_nanosleep_ok=yes])
   if test "x$acx_nanosleep_ok" = "xyes"; then
     NANOSLEEP_LIBS="-lrt"
   fi
   LIBS="$OLD_LIBS"
 fi
 if test "x$acx_nanosleep_ok" != "xyes"; then
   AC_MSG_ERROR([cannot find the nanosleep function])
 else
   AC_MSG_RESULT(${NANOSLEEP_LIBS:-no})
 fi
 AC_LANG_RESTORE
])

**Comment by LeeBergstrand** [comment] 2015-02-03 04:37
From source code of google-perftools 2.4:

```
# Check for support for nanosleep.  It's defined in <time.h>, but on
# some systems, such as solaris, you need to link in a library to use it.
# We set acx_nanosleep_ok if nanosleep is supported; in that case,
# NANOSLEEP_LIBS is set to whatever libraries are needed to support
# nanosleep.

AC_DEFUN([ACX_NANOSLEEP],
[AC_MSG_CHECKING(if nanosleep requires any libraries)
 AC_LANG_SAVE
 AC_LANG_C
 acx_nanosleep_ok="no"
 NANOSLEEP_LIBS=
 # For most folks, this should just work
 AC_TRY_LINK([#include <time.h>],
             [static struct timespec ts; nanosleep(&ts, NULL);],
             [acx_nanosleep_ok=yes])
 # For solaris, we may  need -lrt
 if test "x$acx_nanosleep_ok" != "xyes"; then
   OLD_LIBS="$LIBS"
   LIBS="-lrt $LIBS"
   AC_TRY_LINK([#include <time.h>],
               [static struct timespec ts; nanosleep(&ts, NULL);],
               [acx_nanosleep_ok=yes])
   if test "x$acx_nanosleep_ok" = "xyes"; then
     NANOSLEEP_LIBS="-lrt"
   fi
   LIBS="$OLD_LIBS"
 fi
 if test "x$acx_nanosleep_ok" != "xyes"; then
   AC_MSG_ERROR([cannot find the nanosleep function])
 else
   AC_MSG_RESULT(${NANOSLEEP_LIBS:-no})
 fi
 AC_LANG_RESTORE
])
```

**Comment by saketkc** [comment] 2015-02-03 05:16
Isn't it explained by https://bugs.launchpad.net/ubuntu/+source/gcc-4.6/+bug/1269803

**Comment by sjackman** [comment] 2015-02-03 19:36
He's compiling with GCC 4.9 though.

**Comment by sjackman** [comment] 2015-02-03 19:37
I'm back from vacation and can confirm that I see the same error.

**Comment by sjackman** [comment] 2015-02-03 19:40
That is a good lead though, Saket. Oddly `_GLIBCXX_USE_NANOSLEEP` *is* defined for me.

```
$ grep -r _GLIBCXX_USE_NANOSLEEP /gsc/btl/linuxbrew/include/c++/
/gsc/btl/linuxbrew/include/c++/4.9.2/thread:#ifdef _GLIBCXX_USE_NANOSLEEP
/gsc/btl/linuxbrew/include/c++/4.9.2/x86_64-unknown-linux-gnu/bits/c++config.h:#define _GLIBCXX_USE_NANOSLEEP 1
```

**Comment by gawbul** [comment] 2015-05-26 12:19
Same issue here, system gcc is 4.8.3 and seems affected. Like you say, `gcc-4.9` seems to define the macro, but for some reason still fails for me too?

**Comment by gawbul** [comment] 2015-05-26 12:21
I did the following `brew install -i google-perftools` and then included the c++ directory in the `CPPFLAGS ` as follows:

```CPPFLAGS="-I/tf/people/sm1818/.linuxbrew/include -I/tf/people/sm1818/.linuxbrew/include/c++/4.9.2" ./configure --prefix=/tf/people/sm1818/.linuxbrew/Cellar/google-perftools/2.4
```

**Comment by gawbul** [comment] 2015-05-26 12:42
Checking `config.log` shows the following:

```
configure:17496: checking libunwind.h presence
configure:17496: /home/stevemoss/.linuxbrew/bin/gcc-4.9 -E -I/home/stevemoss/.linuxbrew/include conftest.c
In file included from conftest.c:61:0:
/home/stevemoss/.linuxbrew/include/libunwind.h:38:29: fatal error: mach/mach_types.h: No such file or directory
 #include <mach/mach_types.h>
```

**Comment by gawbul** [comment] 2015-05-26 13:17
Solved this issue by doing a `brew remove libunwind-headers`. I then downloaded the latest `libunwind` from http://download.savannah.gnu.org/releases/libunwind/libunwind-1.1.tar.gz. I compiled and installed this to a local prefix using `./configure --prefix=/home/stevemoss/libunwind`. I then ran the `google-perftools` installation as before, but this time pointing to the new `libunwind` directories (**this may seem a bit convoluted, but I don't have sudo access on the server**):

```
CPPFLAGS="-I/home/stevemoss/.linuxbrew/include -I/home/stevemoss/.linuxbrew/include/c++/4.9.2 -I/home/stevemoss/tools/libunwind" LDFLAGS="-L/home/stevemoss/tools/libunwind/lib" ./configure --prefix=/home/stevemoss/.linuxbrew/Cellar/google-perftools/2.4
```

**Comment by sjackman** [comment] 2015-05-26 18:21
Thanks for the troubleshooting, Steve. Would you like to create a formula for `libunwind` for Linuxbrew?

**Comment by sjackman** [comment] 2015-05-26 18:42
`libunwind` was easy to package. I created a formula in b19afa17134ca57646eebc9ed1f56152067a583e. Would you be able to test it out, Steve?

**Comment by gawbul** [comment] 2015-05-26 18:51
I got this to work by manually compiling and linking against libunwind using `CPPFLAGS="-I/home/stevemoss/.linuxbrew/include -I/home/stevemoss/.linuxbrew/include/c++/4.9.2 -I/home/stevemoss/tools/libunwind" LDFLAGS="-L/home/stevemoss/tools/libunwind/lib" ./configure --prefix=/home/stevemoss/.linuxbrew/Cellar/google-perftools/2.4/` and then `brew link google-perftools`.

**Comment by gawbul** [comment] 2015-05-26 18:51
Ah, just seen your comments, @sjackman. Will give it a whirl :smile:

**Comment by sjackman** [comment] 2015-05-26 18:58
I'm quite confused why adding `~/.linuxbrew/include/c++/4.9.2` manually should be necessary. Shouldn't `g++` include that in its search path by default?

**Comment by gawbul** [comment] 2015-05-26 18:58
@sjackman Worked for me :+1: :smile: 

```
$ brew install libunwind.rb
==> Downloading http://download.savannah.gnu.org/releases/libunwind/libunwind-1.1.tar.gz
Already downloaded: /home/stevemoss/.cache/Homebrew/libunwind-1.1.tar.gz
==> ./configure --prefix=/home/stevemoss/.linuxbrew/Cellar/libunwind/1.1 --disable-silent-rules
==> make install
/home/stevemoss/.linuxbrew/Cellar/libunwind/1.1: 59 files, 764K, built in 22 seconds
```

**Comment by gawbul** [comment] 2015-05-26 19:00
@sjackman It probably doesn't need that, but it had `libunwind.h` in initially, which is why I included it. I think it was more a combination of the headers and libraries missing initially that was causing it to fail. I'll try building now with the `libunwind` formula installed.

**Comment by sjackman** [comment] 2015-05-26 19:15
I have this problem:
```
configure:17496: checking libunwind.h usability
configure:17496: /gsc/btl/linuxbrew/bin/gcc-4.9 -c -Os -w -pipe -march=core2 -D_
XOPEN_SOURCE -isystem/gsc/btl/linuxbrew/include conftest.c >&5
In file included from /gsc/btl/linuxbrew/include/ucontext.h:26:0,
                 from /gsc/btl/linuxbrew/include/libunwind-x86_64.h:37,
                 from /gsc/btl/linuxbrew/include/libunwind.h:23,
                 from conftest.c:91:
/gsc/btl/linuxbrew/include/sys/ucontext.h:137:5: error: unknown type name 'stack
_t'
     stack_t uc_stack;
     ^
configure:17496: $? = 1
```

**Comment by gawbul** [comment] 2015-05-26 19:24
@sjackman Just tried installing `google-perftools` with the homebrew `libunwind` installed and it still fails. Manually installing with just `CPPFLAGS="-I/home/stevemoss/tools/libunwind/include" LDFLAGS="-L/home/stevemoss/tools/libunwind/lib" ./configure --prefix="/home/stevemoss/.linuxbrew/Cellar/google-perfools/2.4"` works fine still. Something weird with the homebrew env?

**Comment by gawbul** [comment] 2015-05-26 19:26
Two interesting things I notice are

```
checking ucontext.h usability... no
checking ucontext.h presence... yes
configure: WARNING: ucontext.h: present but cannot be compiled
configure: WARNING: ucontext.h:     check for missing prerequisite headers?
configure: WARNING: ucontext.h: see the Autoconf documentation
configure: WARNING: ucontext.h:     section "Present But Cannot Be Compiled"
configure: WARNING: ucontext.h: proceeding with the compiler's result
configure: WARNING:     ## ------------------------------------------------ ##
configure: WARNING:     ## Report this to google-perftools@googlegroups.com ##
configure: WARNING:     ## ------------------------------------------------ ##
checking for ucontext.h... no
checking sys/ucontext.h usability... no
checking sys/ucontext.h presence... yes
configure: WARNING: sys/ucontext.h: present but cannot be compiled
configure: WARNING: sys/ucontext.h:     check for missing prerequisite headers?
configure: WARNING: sys/ucontext.h: see the Autoconf documentation
configure: WARNING: sys/ucontext.h:     section "Present But Cannot Be Compiled"
configure: WARNING: sys/ucontext.h: proceeding with the compiler's result
configure: WARNING:     ## ------------------------------------------------ ##
configure: WARNING:     ## Report this to google-perftools@googlegroups.com ##
configure: WARNING:     ## ------------------------------------------------ ##
checking for sys/ucontext.h... no
```

and

```
checking libunwind.h usability... no
checking libunwind.h presence... yes
configure: WARNING: libunwind.h: present but cannot be compiled
configure: WARNING: libunwind.h:     check for missing prerequisite headers?
configure: WARNING: libunwind.h: see the Autoconf documentation
configure: WARNING: libunwind.h:     section "Present But Cannot Be Compiled"
configure: WARNING: libunwind.h: proceeding with the compiler's result
configure: WARNING:     ## ------------------------------------------------ ##
configure: WARNING:     ## Report this to google-perftools@googlegroups.com ##
configure: WARNING:     ## ------------------------------------------------ ##
checking for libunwind.h... no
checking for backtrace in -lunwind... yes
```

neither of these show up when compiling and linking manually.

**Comment by sjackman** [comment] 2015-05-26 20:08
Hi, Steve. Can you please `brew gist-logs google-perftools`?

**Comment by gawbul** [comment] 2015-05-26 20:55
@sjackman https://gist.github.com/anonymous/17cf1f8e3a97711aa5e3 :smile:

**Comment by sjackman** [comment] 2015-05-26 21:07
Yeah, same issue.
https://gist.github.com/anonymous/17cf1f8e3a97711aa5e3#file-config-log-L1617-L1624
```
configure:17279: checking ucontext.h usability
configure:17279: /tf/people/sm1818/.linuxbrew/bin/gcc-4.9 -c -Os -w -pipe -march=core2 -D_XOPEN_SOURCE -isystem/tf/people/sm1818/.linuxbrew/include conftest.c >&5
In file included from /tf/people/sm1818/.linuxbrew/include/ucontext.h:26:0,
                 from conftest.c:91:
/tf/people/sm1818/.linuxbrew/include/sys/ucontext.h:137:5: error: unknown type name 'stack_t'
     stack_t uc_stack;
     ^
configure:17279: $? = 1
```

**Comment by sjackman** [comment] 2015-05-26 21:08
The issue is that one has to use `gcc -std=gnu11` rather than `-std=c11` to get `stack_t`.
See http://stackoverflow.com/questions/20778735/is-the-type-stack-t-no-longer-defined-on-linux

**Comment by tseemann** [comment] 2015-05-30 03:33
So does this need a patch to the google-perftools for std=c11 ?

**Comment by sjackman** [comment] 2015-06-02 04:56
Yes. `append 'CC', '-std=c11'` should do it.

**Comment by gawbul** [comment] 2015-06-02 17:38
So, adding `ENV.append, "CC", "-std=c11"` to the poretools formula should work?

**Comment by sjackman** [comment] 2015-06-02 19:17
I think it was `google-perftools` that was having this issue with `stack_t`, so add it to that formula.

**Comment by gawbul** [comment] 2015-06-03 15:45
I meant perftools sorry, changed the comment... I've got poretools on the brain, lol!

**Closed** 2017-11-27 02:23 UTC
Labels: build-error
