### ISSUE TITLE
librsvg failed to build on Ubuntu 14.04

### ISSUE THREAD

**Issue by ahoka** [Linuxbrew/legacy-linuxbrew#1009] opened 2016-03-30 11:28 UTC
Build fails with the following error:

```
Last 15 lines from /home/edmmhka/.cache/Homebrew/Logs/librsvg/02.make:
  CC       librsvg_2_la-rsvg-xml.lo
  CC       rsvg_convert-rsvg-convert.o
  CC       rsvg_convert-rsvg-size-callback.o
  CC       librsvg_2_la-librsvg-enum-types.lo
  CCLD     librsvg-2.la
  GISCAN   Rsvg-2.0.gir
  CCLD     rsvg-convert
  GICOMP   Rsvg-2.0.gir
Could not find GIR file 'GdkPixbuf-2.0.gir'; check XDG_DATA_DIRS or use --includedir
error parsing file Rsvg-2.0.gir: Failed to parse included gir GdkPixbuf-2.0
make[2]: *** [Rsvg-2.0.typelib] Error 1
make[2]: Leaving directory `/tmp/librsvg20160330-28807-hjz8jo/librsvg-2.40.13'
make[1]: *** [install-recursive] Error 1
make[1]: Leaving directory `/tmp/librsvg20160330-28807-hjz8jo/librsvg-2.40.13'
make: *** [install] Error 2
```

Logs: https://gist.github.com/c8cf90ae754829e451454b419e547f1b

**Comment by sjackman** [comment] 2016-03-30 17:10
Please surround copied-and-pasted logs with triple back ticks. See [GitHub Help / Quoting Code](https://help.github.com/articles/basic-writing-and-formatting-syntax/#quoting-code).

**Comment by sjackman** [comment] 2016-03-30 17:11
@DoomHammer Piotr, can you reproduce this error?
`Could not find GIR file 'GdkPixbuf-2.0.gir'; check XDG_DATA_DIRS`

**Comment by tseemann** [comment] 2016-03-30 20:42
I built it on RHEL 7 ok, but I also recently rebuilt `cairo --with-x11` after installing `xorg`.

Build: xz ✔, pkg-config ✔
Required: cairo ✔, gdk-pixbuf ✔, glib ✔, libcroco ✔, pango ✔
Optional: gtk+3 ✘, libgsf ✘

**Comment by ahmedmagds** [comment] 2016-03-31 14:58
@tseemann I have the same problem and I cannot install Nullarbor because of this error

**Comment by ahmedmagds** [comment] 2016-04-01 18:27
Please have a look on my log file
https://gist.github.com/f693b60f8182900468fcf3cb9e962216

**Comment by sjackman** [comment] 2016-04-01 18:44
@DoomHammer Would this error be fixed by setting `XDG_DATA_DIRS`?
```
  GICOMP   Rsvg-2.0.gir
Could not find GIR file 'GdkPixbuf-2.0.gir'; check XDG_DATA_DIRS or use --includedir
error parsing file Rsvg-2.0.gir: Failed to parse included gir GdkPixbuf-2.0
make[2]: *** [Rsvg-2.0.typelib] Error 1
```

**Comment by DoomHammer** [comment] 2016-04-01 18:48
This one is not on the [list](https://github.com/Linuxbrew/linuxbrew/issues/899#issuecomment-194797708) but symptoms look similar. It is worth a try.

@ahmedmagds, @ahoka could you do this prior to running `brew`:

```
export XDG_DATA_DIRS=$(brew --prefix)/share:$XDG_DATA_DIRS
```

?

**Comment by ahmedmagds** [comment] 2016-04-01 19:57
the command fixed it, thanks alot

**Comment by tseemann** [comment] 2016-04-01 22:23
Thanks @DoomHammer !

**Comment by DoomHammer** [comment] 2016-04-02 06:36
@tseemann just for the build.

@sjackman we have two proposals right now and I think they are a bit redundant. One is to use `brew doctor` to ensure user sets `$XDG_DATA_DIRS`, the other is to add this to `ENV/std`. Which one should we approach (or both)?

**Comment by sjackman** [comment] 2016-04-03 18:59
Is it only needed for the build? I assumed that it would also be need when you ran the app, so I suggested the `brew doctor` check. If it's only needed for the build, then by all means add it to `ENV/std`, much simpler.

**Closed** 2016-08-11 13:04 UTC
Labels: build-error
