### ISSUE TITLE
homebrew/dupes/xar: recipe for target 'src/ixar' failed

### ISSUE THREAD

**Issue by mistydemeo** [Linuxbrew/legacy-linuxbrew#725] opened 2016-01-17 17:59 UTC
_From @Rudloff on January 17, 2016 16:57_

Hello,

The xar formula does not seem to work on Linux:
https://gist.github.com/Rudloff/d34fac5f7b0631c5bf60

Regards,

_Copied from original issue: Homebrew/homebrew-dupes#563_

**Comment by sjackman** [comment] 2016-01-19 06:53
The relevant error is:
```
/usr/bin/gcc -Os -w -pipe -march=core2  -o src/ixar src/xar.o -Wl,-rpath,/home/pierre/.linuxbrew/Cellar/xar/1.5.2/lib -Llib -L/home/pierre/.linuxbrew/lib -Wl,-rpath,/home/pierre/.linuxbrew/lib  lib/libxar.so.1 -lbz2 -lz -lcrypto  -L/home/pierre/.linuxbrew/Cellar/libxml2/2.9.3/lib -lxml2 -lz -lm -ldl
lib/libxar.so.1: référence indéfinie vers « OpenSSL_add_all_digests@OPENSSL_1.0.0 »
```
https://gist.github.com/Rudloff/d34fac5f7b0631c5bf60#file-02-make-L79-L80

I'm not able to reproduce this error myself. It looks like the xar Makefile is ignoring `CPPFLAGS`, which is resulting in it using the headers of your system's version of OpenSSL, but the libraries of Homebrew's version of OpenSSL. You should report this bug upstream to the `xar` authors. A workaround would be to remove the OpenSSL development package that includes the header files using your system's package manager.

**Comment by Rudloff** [comment] 2016-01-19 21:37
The upstream project does not seem to be maintained anymore but the fix would be quite easy to include in the Formula:
```diff
diff --git a/xar.rb b/xar.rb
index eaebb66..94efda1 100644
--- a/xar.rb
+++ b/xar.rb
@@ -20,6 +20,7 @@ class Xar < Formula
   patch :DATA
 
   def install
+    inreplace "lib/Makefile.inc.in", "$(CC) -shared -Wl,-soname,$(LIBXAR_SNAME) -o $@ $+ @LIBS", "$(CC) $(LDFLAGS) -shared -Wl,-soname,$(LIBXAR_SNAME) -o $@ $+ @LIBS"
     system "./configure", "--disable-debug", "--disable-dependency-tracking",
                           "--prefix=#{prefix}", "--mandir=#{man}"
     system "make"
```

**Comment by sjackman** [comment] 2016-01-20 01:09
I don't unfortunately have commit permissions to `homebrew/dupes`.

**Comment by sjackman** [comment] 2016-01-20 01:10
Superenv would probably fix this. See #266

**Comment by Rudloff** [comment] 2016-01-20 09:58
Do you think I should report it to homebrew-dupes ?

**Comment by sjackman** [comment] 2016-01-20 16:25
Misty moved this issue here from homebrew-dupes. The fix should go upstream. Maintaining abandoned software is a pain.

`-L#{HOMEBREW_PREFIX}/lib` already appears on the link line, so it appears to be respecting `LDFLAGS` already:

https://gist.github.com/Rudloff/d34fac5f7b0631c5bf60#file-02-make-L79
`/usr/bin/gcc -Os -w -pipe -march=core2  -o src/ixar src/xar.o -Wl,-rpath,/home/pierre/.linuxbrew/Cellar/xar/1.5.2/lib -Llib -L/home/pierre/.linuxbrew/lib -Wl,-rpath,/home/pierre/.linuxbrew/lib  lib/libxar.so.1 -lbz2 -lz -lcrypto  -L/home/pierre/.linuxbrew/Cellar/libxml2/2.9.3/lib -lxml2 -lz -lm -ldl`
Does the above patch fix your issue?

I take back what I said previously about it not respecting `CPPFLAGS`. I also see `-isystem/home/pierre/.linuxbrew/include` on the compiler line:
https://gist.github.com/Rudloff/d34fac5f7b0631c5bf60#file-02-make-L46
`/usr/bin/gcc -Os -w -pipe -march=core2   -Iinclude -Iinclude -isystem/home/pierre/.linuxbrew/include -D_GNU_SOURCE -I/home/pierre/.linuxbrew/Cellar/libxml2/2.9.3/include/libxml2 -c lib/macho.c -o lib/macho.static.o`

I'm not sure exactly where the problem is. Sometimes the particular order of the search path is wrong.

**Comment by Rudloff** [comment] 2016-01-20 16:30
Yes, the patch I posted does fix the issue for me but I'm not sure why.

**Comment by sjackman** [comment] 2016-01-20 17:09
I'll take a closer look…

**Comment by sjackman** [comment] 2016-01-20 23:45
Oh, yes. I see now. It does use `LDFLAGS` when linking executables, but not when linking shared libraries.
https://gist.github.com/Rudloff/d34fac5f7b0631c5bf60#file-02-make-L50
```
/usr/bin/gcc -shared -Wl,-soname,libxar.so.1 -o lib/libxar.so.1 lib/archive.o lib/arcmod.o lib/b64.o lib/bzxar.o lib/darwinattr.o lib/data.o lib/ea.o lib/err.o lib/ext2.o lib/fbsdattr.o lib/filetree.o lib/io.o lib/linuxattr.o lib/hash.o lib/signature.o lib/stat.o lib/subdoc.o lib/util.o lib/zxar.o lib/script.o lib/macho.o -lbz2 -lz -lcrypto  -L/home/pierre/.linuxbrew/Cellar/libxml2/2.9.3/lib -lxml2 -lz -lm -ldl
```

Can you try a smaller patch, something like (untesed)…
```diff
diff --git a/xar.rb b/xar.rb
index eaebb66..94efda1 100644
--- a/xar.rb
+++ b/xar.rb
@@ -20,6 +20,7 @@ class Xar < Formula
   patch :DATA

   def install
+    inreplace "lib/Makefile.inc.in", "$(CC) -shared", "$(CC) $(LDFLAGS) -shared"
     system "./configure", "--disable-debug", "--disable-dependency-tracking",
                           "--prefix=#{prefix}", "--mandir=#{man}"
     system "make"
```

**Comment by sjackman** [comment] 2016-01-20 23:46
@mistydemeo `xar` ignores `LDFLAGS` when linking shared libraries, which can cause errors on Linuxbrew (or possibly on Homebrew with `--env=std`). Would you consider applying the above patch to `Homebrew/dupes/xar`?

**Comment by Rudloff** [comment] 2016-01-20 23:53
@sjackman Yes, your smaller patch works too.

**Comment by rwhogg** [comment] 2017-02-23 06:23
Closing since `homebrew/dupes/xar` was deleted.

**Closed by rwhogg** 2017-02-23 06:23 UTC
Labels: build-error, unreproducible, upstream
